baseURL: "https://betterindata.com/"
languageCode: "en-us"
title: "betterindata"

sitemap:
  changefreq: weekly

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    parser:
      block: true

  highlight:
    style: "vulcan"
    tabWidth: 4
