baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My New Hugo Site'

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

outputs:
  home:
    - html
    - rss
    - json