baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My New Hugo Site'
canonifyURLs: true

sitemap:
  changefreq: weekly

permalinks:
  lessons: "/:year/:month/:slug/"
  projects: "/:year/:month/:slug/"
  page: "/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

outputs:
  home:
    - html
    - rss
    - json