baseURL: 'https://betterindata.com/'
languageCode: 'en-us'
title: 'better in data'
canonifyURLs: true

sitemap:
  changefreq: weekly

permalinks:
  lessons: "/:year/:month/:slug/"
  projects: "/:year/:month/:slug/"
  page: "/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    parser:
      attribute:
        block: true
  highlight:
    style: 'vulcan'
    tabWidth: 4